### ISSUE TITLE
What happen ?

### ISSUE THREAD

**Issue by nicejava** [sid5432/pyOTDR#12]
![image](https://user-images.githubusercontent.com/6760497/61730151-ff3ce980-ada2-11e9-90bb-74fef2802153.png)

**Comment by sid5432** [comment]
The issue seems to be with the "utils" module. It is specified in the requirements.txt listing, but it seems that it is not working or was not installed correctly on your computer. The installation (with python -m pip install pyOTDR) works without problem in Linux (latest Ubuntu); I don't have a Windows machine to try this, but try installing "utils" explicitly first (python -m pip install utils) and then try again, and see if it works. You may need to uninstall utils first.

**Comment by nicejava** [comment]
After install utils not solved my problem ..

![image](https://user-images.githubusercontent.com/6760497/61761870-4609fe00-adfa-11e9-9e31-1fe04e85ee24.png)

**Comment by nicejava** [comment]
My problem solved find it my self , Edit in setup.py in lazyxml-1.2.1 ( download file on website extension is .tar.gz and extract it )

Replace like this

with open('README.rst', 'r', encoding='UTF-8') as fp:
    readme = fp.read()

with open('LICENSE', 'r', encoding='UTF-8') as fp:
    license = fp.read()

And try "python setup.py install" (in lazyxml-1.2.1 folder ) 
and try python -m pip install pyOTDR again
.. Working done

Thank you ..

**Comment by sid5432** [comment]
Thanks for sharing your solution. I will close this issue now. Thanks.
