### ISSUE TITLE
pip install pyOTDR fail

### ISSUE THREAD

**Issue by FriedrichWilhelmNietzsche** [sid5432/pyOTDR#9]
![image](https://user-images.githubusercontent.com/30073072/50395765-0108e500-07a1-11e9-9d87-929959e35bcd.png)

**Comment by sid5432** [comment]
I have only run this in Linux, so I am not sure what the problem is. It may be related to a multi-byte encoding issue (there is a posting at [https://github.com/bndr/pipreqs/issues/125](https://github.com/bndr/pipreqs/issues/125) that might be relevant to the problem), but I do not know how to fix this. The trouble seems to be in the lazyxml module; RemiDesgrange has comments about problems with installing lazyxml, and suggested that I switch to some other package to handle the conversion to/from XML (I haven't looked at his fork, but maybe you can try [his code](https://github.com/RemiDesgrange/pyOTDR) and see if that works for you). Unfortunately I never got around doing that. Maybe I'll take that up as a New Year's resolution for 2019!

**Comment by FriedrichWilhelmNietzsche** [comment]
Thanks for your prompt reply.

I changed the 19th line as "with open('README.rst', 'r', encoding='UTF-8') as fp:"  in " setup.py " file { [[lazyxml-1.2.1]](https://files.pythonhosted.org/packages/eb/ca/9fe2223845fb0e6637a99fe485fc3535e471b12e4a016332c9cabf0264a6/lazyxml-1.2.1.tar.gz) }  , and installed, 
after that, pip install pyOTDR, it works. 

![image](https://user-images.githubusercontent.com/30073072/50412922-3287bc00-0846-11e9-94de-3f46eb64fc8b.png)

**Comment by vivindeveloper** [comment]
I am facing the same issue in windows. can you tell me where the folder setup.py is located please

**Comment by sid5432** [comment]
I assume you are talking about "setup.py" in the [lazyxml](https://github.com/heronotears/lazyxml) package? It should be in the top directory if you download the package.
